// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Docker-based backend or Cloud.
///
/// This is a PLACEHOLDER file.
/// You should overwrite this by running `flutterfire configure`.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // WEB
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_API_KEY_WEB'),
    appId: '1:36853289802:web:b49171c09b4114c2c027b3',
    messagingSenderId: '36853289802',
    projectId: 'samriddhiflow',
    authDomain: 'samriddhiflow.web.app',
    storageBucket: 'samriddhiflow.firebasestorage.app',
  );

  // ANDROID
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_API_KEY_ANDROID'),
    appId: '1:36853289802:android:47e2dce1397e89eac027b3',
    messagingSenderId: '36853289802',
    projectId: 'samriddhiflow',
    storageBucket: 'samriddhiflow.firebasestorage.app',
  );

  // WINDOWS (Uses Web Key if typically same but separate option here)
  // Originally visible key was same as Web: AIza...e2w
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_API_KEY_WINDOWS'),
    appId: '1:36853289802:web:dd3bf3b583b1dfa2c027b3',
    messagingSenderId: '36853289802',
    projectId: 'samriddhiflow',
    authDomain: 'samriddhiflow.web.app',
    storageBucket: 'samriddhiflow.firebasestorage.app',
  );
}
