// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:samriddhi_flow/models/account.dart';
import 'package:samriddhi_flow/models/category.dart';
import 'package:samriddhi_flow/models/lending_record.dart';
import 'package:samriddhi_flow/models/loan.dart';
import 'package:samriddhi_flow/models/profile.dart';
import 'package:samriddhi_flow/models/recurring_transaction.dart';
import 'package:samriddhi_flow/models/taxes/insurance_policy.dart';
import 'package:samriddhi_flow/models/taxes/tax_data.dart';
import 'package:samriddhi_flow/models/taxes/tax_data_models.dart';
import 'package:samriddhi_flow/models/taxes/tax_rules.dart';
import 'package:samriddhi_flow/models/transaction.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AccountAdapter());
    registerAdapter(AccountTypeAdapter());
    registerAdapter(AssetTypeAdapter());
    registerAdapter(BusinessEntityAdapter());
    registerAdapter(BusinessTypeAdapter());
    registerAdapter(CapitalGainEntryAdapter());
    registerAdapter(CategoryAdapter());
    registerAdapter(CategoryTagAdapter());
    registerAdapter(CategoryUsageAdapter());
    registerAdapter(CustomAllowanceAdapter());
    registerAdapter(CustomDeductionAdapter());
    registerAdapter(CustomExemptionAdapter());
    registerAdapter(DividendIncomeAdapter());
    registerAdapter(FrequencyAdapter());
    registerAdapter(HousePropertyAdapter());
    registerAdapter(InsurancePolicyAdapter());
    registerAdapter(InsurancePremiumRuleAdapter());
    registerAdapter(LendingRecordAdapter());
    registerAdapter(LendingTypeAdapter());
    registerAdapter(LoanAdapter());
    registerAdapter(LoanTransactionAdapter());
    registerAdapter(LoanTransactionTypeAdapter());
    registerAdapter(LoanTypeAdapter());
    registerAdapter(OtherIncomeAdapter());
    registerAdapter(PayoutFrequencyAdapter());
    registerAdapter(ProfileAdapter());
    registerAdapter(RecurringTransactionAdapter());
    registerAdapter(ReinvestmentTypeAdapter());
    registerAdapter(SalaryDetailsAdapter());
    registerAdapter(SalaryStructureAdapter());
    registerAdapter(ScheduleTypeAdapter());
    registerAdapter(TaxExemptionRuleAdapter());
    registerAdapter(TaxMappingRuleAdapter());
    registerAdapter(TaxPaymentEntryAdapter());
    registerAdapter(TaxRulesAdapter());
    registerAdapter(TaxSlabAdapter());
    registerAdapter(TaxYearDataAdapter());
    registerAdapter(TransactionAdapter());
    registerAdapter(TransactionTypeAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AccountAdapter());
    registerAdapter(AccountTypeAdapter());
    registerAdapter(AssetTypeAdapter());
    registerAdapter(BusinessEntityAdapter());
    registerAdapter(BusinessTypeAdapter());
    registerAdapter(CapitalGainEntryAdapter());
    registerAdapter(CategoryAdapter());
    registerAdapter(CategoryTagAdapter());
    registerAdapter(CategoryUsageAdapter());
    registerAdapter(CustomAllowanceAdapter());
    registerAdapter(CustomDeductionAdapter());
    registerAdapter(CustomExemptionAdapter());
    registerAdapter(DividendIncomeAdapter());
    registerAdapter(FrequencyAdapter());
    registerAdapter(HousePropertyAdapter());
    registerAdapter(InsurancePolicyAdapter());
    registerAdapter(InsurancePremiumRuleAdapter());
    registerAdapter(LendingRecordAdapter());
    registerAdapter(LendingTypeAdapter());
    registerAdapter(LoanAdapter());
    registerAdapter(LoanTransactionAdapter());
    registerAdapter(LoanTransactionTypeAdapter());
    registerAdapter(LoanTypeAdapter());
    registerAdapter(OtherIncomeAdapter());
    registerAdapter(PayoutFrequencyAdapter());
    registerAdapter(ProfileAdapter());
    registerAdapter(RecurringTransactionAdapter());
    registerAdapter(ReinvestmentTypeAdapter());
    registerAdapter(SalaryDetailsAdapter());
    registerAdapter(SalaryStructureAdapter());
    registerAdapter(ScheduleTypeAdapter());
    registerAdapter(TaxExemptionRuleAdapter());
    registerAdapter(TaxMappingRuleAdapter());
    registerAdapter(TaxPaymentEntryAdapter());
    registerAdapter(TaxRulesAdapter());
    registerAdapter(TaxSlabAdapter());
    registerAdapter(TaxYearDataAdapter());
    registerAdapter(TransactionAdapter());
    registerAdapter(TransactionTypeAdapter());
  }
}
