// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:samriddhi_flow/models/account.dart';
import 'package:samriddhi_flow/models/category.dart';
import 'package:samriddhi_flow/models/loan.dart';
import 'package:samriddhi_flow/models/profile.dart';
import 'package:samriddhi_flow/models/recurring_transaction.dart';
import 'package:samriddhi_flow/models/transaction.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AccountAdapter());
    registerAdapter(AccountTypeAdapter());
    registerAdapter(CategoryAdapter());
    registerAdapter(CategoryTagAdapter());
    registerAdapter(CategoryUsageAdapter());
    registerAdapter(FrequencyAdapter());
    registerAdapter(LoanAdapter());
    registerAdapter(LoanTransactionAdapter());
    registerAdapter(LoanTransactionTypeAdapter());
    registerAdapter(LoanTypeAdapter());
    registerAdapter(ProfileAdapter());
    registerAdapter(RecurringTransactionAdapter());
    registerAdapter(ScheduleTypeAdapter());
    registerAdapter(TransactionAdapter());
    registerAdapter(TransactionTypeAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AccountAdapter());
    registerAdapter(AccountTypeAdapter());
    registerAdapter(CategoryAdapter());
    registerAdapter(CategoryTagAdapter());
    registerAdapter(CategoryUsageAdapter());
    registerAdapter(FrequencyAdapter());
    registerAdapter(LoanAdapter());
    registerAdapter(LoanTransactionAdapter());
    registerAdapter(LoanTransactionTypeAdapter());
    registerAdapter(LoanTypeAdapter());
    registerAdapter(ProfileAdapter());
    registerAdapter(RecurringTransactionAdapter());
    registerAdapter(ScheduleTypeAdapter());
    registerAdapter(TransactionAdapter());
    registerAdapter(TransactionTypeAdapter());
  }
}
