// Mocks generated by Mockito 5.4.6 from annotations
// in samriddhi_flow/test/unit/notification_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:samriddhi_flow/models/account.dart' as _i6;
import 'package:samriddhi_flow/models/category.dart' as _i10;
import 'package:samriddhi_flow/models/loan.dart' as _i8;
import 'package:samriddhi_flow/models/profile.dart' as _i5;
import 'package:samriddhi_flow/models/recurring_transaction.dart' as _i9;
import 'package:samriddhi_flow/models/transaction.dart' as _i7;
import 'package:samriddhi_flow/services/storage_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i2.StorageService {
  MockStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  String getActiveProfileId() => (super.noSuchMethod(
        Invocation.method(
          #getActiveProfileId,
          [],
        ),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.method(
            #getActiveProfileId,
            [],
          ),
        ),
      ) as String);

  @override
  _i3.Future<void> setActiveProfileId(String? id) => (super.noSuchMethod(
        Invocation.method(
          #setActiveProfileId,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  bool getAuthFlag() => (super.noSuchMethod(
        Invocation.method(
          #getAuthFlag,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<void> setAuthFlag(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setAuthFlag,
          [value],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  bool isSmartCalculatorEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isSmartCalculatorEnabled,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<void> setSmartCalculatorEnabled(bool? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSmartCalculatorEnabled,
          [value],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  List<_i5.Profile> getProfiles() => (super.noSuchMethod(
        Invocation.method(
          #getProfiles,
          [],
        ),
        returnValue: <_i5.Profile>[],
      ) as List<_i5.Profile>);

  @override
  _i3.Future<void> saveProfile(_i5.Profile? profile) => (super.noSuchMethod(
        Invocation.method(
          #saveProfile,
          [profile],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteProfile(String? profileId) => (super.noSuchMethod(
        Invocation.method(
          #deleteProfile,
          [profileId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  List<_i6.Account> getAccounts() => (super.noSuchMethod(
        Invocation.method(
          #getAccounts,
          [],
        ),
        returnValue: <_i6.Account>[],
      ) as List<_i6.Account>);

  @override
  List<_i6.Account> getAllAccounts() => (super.noSuchMethod(
        Invocation.method(
          #getAllAccounts,
          [],
        ),
        returnValue: <_i6.Account>[],
      ) as List<_i6.Account>);

  @override
  _i3.Future<void> saveAccount(_i6.Account? account) => (super.noSuchMethod(
        Invocation.method(
          #saveAccount,
          [account],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteAccount(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteAccount,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  List<_i7.Transaction> getTransactions() => (super.noSuchMethod(
        Invocation.method(
          #getTransactions,
          [],
        ),
        returnValue: <_i7.Transaction>[],
      ) as List<_i7.Transaction>);

  @override
  List<_i7.Transaction> getAllTransactions() => (super.noSuchMethod(
        Invocation.method(
          #getAllTransactions,
          [],
        ),
        returnValue: <_i7.Transaction>[],
      ) as List<_i7.Transaction>);

  @override
  List<_i7.Transaction> getDeletedTransactions() => (super.noSuchMethod(
        Invocation.method(
          #getDeletedTransactions,
          [],
        ),
        returnValue: <_i7.Transaction>[],
      ) as List<_i7.Transaction>);

  @override
  _i3.Future<void> checkCreditCardRollovers() => (super.noSuchMethod(
        Invocation.method(
          #checkCreditCardRollovers,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> saveTransaction(
    _i7.Transaction? transaction, {
    bool? applyImpact = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveTransaction,
          [transaction],
          {#applyImpact: applyImpact},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> saveTransactions(
    List<_i7.Transaction>? transactions, {
    bool? applyImpact = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveTransactions,
          [transactions],
          {#applyImpact: applyImpact},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  int getTxnsSinceBackup() => (super.noSuchMethod(
        Invocation.method(
          #getTxnsSinceBackup,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  _i3.Future<void> resetTxnsSinceBackup() => (super.noSuchMethod(
        Invocation.method(
          #resetTxnsSinceBackup,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteTransaction(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteTransaction,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<int> getSimilarTransactionCount(
    String? title,
    String? category,
    String? excludeId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSimilarTransactionCount,
          [
            title,
            category,
            excludeId,
          ],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<void> bulkUpdateCategory(
    String? title,
    String? oldCategory,
    String? newCategory,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #bulkUpdateCategory,
          [
            title,
            oldCategory,
            newCategory,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> restoreTransaction(String? id) => (super.noSuchMethod(
        Invocation.method(
          #restoreTransaction,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> permanentlyDeleteTransaction(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #permanentlyDeleteTransaction,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  List<_i8.Loan> getLoans() => (super.noSuchMethod(
        Invocation.method(
          #getLoans,
          [],
        ),
        returnValue: <_i8.Loan>[],
      ) as List<_i8.Loan>);

  @override
  List<_i8.Loan> getAllLoans() => (super.noSuchMethod(
        Invocation.method(
          #getAllLoans,
          [],
        ),
        returnValue: <_i8.Loan>[],
      ) as List<_i8.Loan>);

  @override
  _i3.Future<void> saveLoan(_i8.Loan? loan) => (super.noSuchMethod(
        Invocation.method(
          #saveLoan,
          [loan],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteLoan(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteLoan,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  List<_i9.RecurringTransaction> getRecurring() => (super.noSuchMethod(
        Invocation.method(
          #getRecurring,
          [],
        ),
        returnValue: <_i9.RecurringTransaction>[],
      ) as List<_i9.RecurringTransaction>);

  @override
  List<_i9.RecurringTransaction> getAllRecurring() => (super.noSuchMethod(
        Invocation.method(
          #getAllRecurring,
          [],
        ),
        returnValue: <_i9.RecurringTransaction>[],
      ) as List<_i9.RecurringTransaction>);

  @override
  _i3.Future<void> saveRecurringTransaction(_i9.RecurringTransaction? rt) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveRecurringTransaction,
          [rt],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteRecurringTransaction(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteRecurringTransaction,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> advanceRecurringTransactionDate(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #advanceRecurringTransactionDate,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  List<_i10.Category> getCategories() => (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [],
        ),
        returnValue: <_i10.Category>[],
      ) as List<_i10.Category>);

  @override
  List<_i10.Category> getAllCategories() => (super.noSuchMethod(
        Invocation.method(
          #getAllCategories,
          [],
        ),
        returnValue: <_i10.Category>[],
      ) as List<_i10.Category>);

  @override
  _i3.Future<void> addCategory(_i10.Category? category) => (super.noSuchMethod(
        Invocation.method(
          #addCategory,
          [category],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> removeCategory(String? id) => (super.noSuchMethod(
        Invocation.method(
          #removeCategory,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateCategory(
    String? id, {
    required String? name,
    required _i10.CategoryUsage? usage,
    required _i10.CategoryTag? tag,
    required int? iconCode,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCategory,
          [id],
          {
            #name: name,
            #usage: usage,
            #tag: tag,
            #iconCode: iconCode,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> copyCategories(
    String? fromId,
    String? toId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #copyCategories,
          [
            fromId,
            toId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  String getCurrencyLocale() => (super.noSuchMethod(
        Invocation.method(
          #getCurrencyLocale,
          [],
        ),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.method(
            #getCurrencyLocale,
            [],
          ),
        ),
      ) as String);

  @override
  _i3.Future<void> setCurrencyLocale(String? locale) => (super.noSuchMethod(
        Invocation.method(
          #setCurrencyLocale,
          [locale],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  double getMonthlyBudget() => (super.noSuchMethod(
        Invocation.method(
          #getMonthlyBudget,
          [],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  _i3.Future<void> setMonthlyBudget(double? budget) => (super.noSuchMethod(
        Invocation.method(
          #setMonthlyBudget,
          [budget],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  int getBackupThreshold() => (super.noSuchMethod(
        Invocation.method(
          #getBackupThreshold,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  _i3.Future<void> setBackupThreshold(int? threshold) => (super.noSuchMethod(
        Invocation.method(
          #setBackupThreshold,
          [threshold],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  List<DateTime> getHolidays() => (super.noSuchMethod(
        Invocation.method(
          #getHolidays,
          [],
        ),
        returnValue: <DateTime>[],
      ) as List<DateTime>);

  @override
  _i3.Future<void> addHoliday(DateTime? date) => (super.noSuchMethod(
        Invocation.method(
          #addHoliday,
          [date],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> removeHoliday(DateTime? date) => (super.noSuchMethod(
        Invocation.method(
          #removeHoliday,
          [date],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> setLastLogin(DateTime? date) => (super.noSuchMethod(
        Invocation.method(
          #setLastLogin,
          [date],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  int getInactivityThresholdDays() => (super.noSuchMethod(
        Invocation.method(
          #getInactivityThresholdDays,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  _i3.Future<void> setInactivityThresholdDays(int? days) => (super.noSuchMethod(
        Invocation.method(
          #setInactivityThresholdDays,
          [days],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  int getMaturityWarningDays() => (super.noSuchMethod(
        Invocation.method(
          #getMaturityWarningDays,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  _i3.Future<void> setMaturityWarningDays(int? days) => (super.noSuchMethod(
        Invocation.method(
          #setMaturityWarningDays,
          [days],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  bool isAppLockEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isAppLockEnabled,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<void> setAppLockEnabled(bool? enabled) => (super.noSuchMethod(
        Invocation.method(
          #setAppLockEnabled,
          [enabled],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> setAppPin(String? pin) => (super.noSuchMethod(
        Invocation.method(
          #setAppPin,
          [pin],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  String getThemeMode() => (super.noSuchMethod(
        Invocation.method(
          #getThemeMode,
          [],
        ),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.method(
            #getThemeMode,
            [],
          ),
        ),
      ) as String);

  @override
  _i3.Future<void> setThemeMode(String? mode) => (super.noSuchMethod(
        Invocation.method(
          #setThemeMode,
          [mode],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> clearAllData() => (super.noSuchMethod(
        Invocation.method(
          #clearAllData,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
