name: Main Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    types: [synchronize]

jobs:
  build-and-test:
    uses: ./.github/workflows/build-test.yml
    secrets: inherit

  sonarcloud:
    needs: build-and-test
    uses: ./.github/workflows/sonarcloud.yml
    secrets: inherit

  deploy:
    needs: sonarcloud
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
    secrets: inherit